name: Build OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Init Env
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone Source
      run: git clone --depth 1 "https://github.com/openwrt/openwrt.git" -b openwrt-23.05 openwrt

    - name: Update & Install Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Patch Podkop & Config
      run: |
        cd openwrt
        rm -rf feeds/packages/net/podkop
        git clone "https://github.com/itdoginfo/podkop.git" package/podkop
        echo "CONFIG_TARGET_ramips=y" > .config
        echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
        echo "CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-4a-gigabit=y" >> .config
        echo "CONFIG_TARGET_ROOTFS_INITRAMFS=y" >> .config
        echo "CONFIG_PACKAGE_luci=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-russian=y" >> .config
        echo "CONFIG_PACKAGE_podkop=y" >> .config
        make defconfig

    - name: Download
      run: cd openwrt && make download -j8

    - name: Compile
      run: cd openwrt && make -j$(nproc) || make -j1 V=s

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_Firmware
        path: openwrt/bin/targets/ramips/mt7621/*.bin
